apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: financeiro
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: gateway
