apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: financeiro
type: Opaque
stringData:
  # Users Database
  users-db-name: "financeiro_users"
  users-db-user: "<USERNAME>"
  users-db-password: "<PASSWORD>" # Replace with a strong password

  # Authentication Database
  auth-db-name: "financeiro_authentication"
  auth-db-user: "<USERNAME>"
  auth-db-password: "<PASSWORD>"  # Replace with a strong password

  # Notification Database
  notification-db-name: "financeiro_notification"
  notification-db-user: "<USERNAME>"
  notification-db-password: "<PASSWORD>"  # Replace with a strong password

  # Postgres Admin
  postgres-admin-password: "<PASSWORD>"  # Replace with a strong password
