apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: financeiro
type: Opaque
stringData:
  rabbitmq-username: "<USERNAME>"
  rabbitmq-password: "<PASSWORD>" # Change this to a strong password
  rabbitmq-erlang-cookie: "<ERLANG_COOKIE>"
