apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: financeiro
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: frontend
---
# Setup Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: financeiro
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # Request certificate from Let's Encrypt
    cert-manager.io/cluster-issuer: letsencrypt-production
    # Enable TLS/SSL
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: financeiro-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: <YOUR_DOMAIN_URL>  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  # To enable HTTPS, add a tls section like below and ensure the secret exists:
  tls:
  - hosts:
      - <YOUR_DOMAIN_URL>
    secretName: frontend-tls-cert
