apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: financeiro
type: Opaque
stringData:
  users-db-url: "postgresql://<USERNAME>:<PASSWORD>@postgres-users:5432/financeiro_users?sslmode=disable"
  auth-db-url: "postgresql://<USERNAME>:<PASSWORD>@postgres-auth:5432/financeiro_authentication?sslmode=disable"
  notification-db-url: "postgresql://<USERNAME>:<PASSWORD>@postgres-notification:5432/financeiro_notification?sslmode=disable"
