apiVersion: v1
kind: Secret
metadata:
  name: email-secrets
  namespace: financeiro
type: Opaque
stringData:
  smtp_port: "587"
  smtp_from: "<SMTP_FROM>"
  smtp_username: "<SMTP_USERNAME>"
  smtp_password: "<SMTP_PASSWORD>"
